---

- name: Download if exe not present
  get_url: url={{ item }} dest=../iso/ force=no
  with_items:
  - {{ c6isourl }}
  - {{ cs_centos53x64_template }}
  - {{ packer }}
  - {{ workstation_bundle }}
  - {{ vix_bundle }}

- name: Install packer
  copy: src="../iso/packer" dest="/usr/bin/packer" mode=0777

- name: install workstation
  shell: "../iso/base({{ workstation_bundle }})"

  