---

- name: install setup tools
  yum: name={{ item }} state=present
  with_items:
    - python-setuptools
    - epel-release
    - jq

- name: ensure cm config is removed
  file: path=/root/.cloudmonkey/config state=absent

- name: install cloudmonkey
  shell: easy_install cloudmonkey

- name: base configuration
  shell: cloudmonkey {{ item }}
  with_items:
    - "set prompt '{{ bc_cmprompt }}>'"
    - "set history_file /usr/share/cloudmonkey_history"
    - "set log_file /var/log/cloudmonkey"
    - "set display json"
    - "set username admin"
    - "set password password"
    - "set url http://{{ bc_mgmtip }}:8080/client/api"
#    - "set apikey TBC"
#    - "set secretkey TBC"
