---

- name: update mysql root password for localhost root accounts
  mysql_user: user="{{ bc_rootuser }}" password="{{ bc_rootpwd }}" host=localhost login_user="{{ bc_rootuser }}" login_password=""
  ignore_errors: true

- name: remove the MySQL test database
  mysql_db: db=test state=absent login_user="{{ bc_rootuser }}" login_password="{{ bc_rootpwd }}"
  ignore_errors: true

- name: update mysql root password for all other root accounts
  mysql_user: user="{{ bc_rootuser }}" password="{{ bc_rootpwd }}" host="{{ item }}" login_user="{{ bc_rootuser }}" login_password="{{ bc_rootpwd }}"
  with_items:
    - 127.0.0.1
    - "%"
    - "::1"
  ignore_errors: true

- name: remove empty users
  mysql_user: login_user={{ bc_rootuser }} login_password="{{ bc_rootpwd }}" name='' host={{ item }} state=absent
  with_items:
    - 127.0.0.1
    - localhost
    - "{{ ansible_hostname }}"
    - "%"
  ignore_errors: true

- name: delete anonymous MySQL server user for ansible_hostname
  mysql_user: user='' host="{{ item }}" state="absent" login_user="{{ bc_rootuser }}" login_password="{{ bc_rootpwd }}"
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
    - "%"
    - 127.0.0.1
    - "::1"
  ignore_errors: true

- name: remove IPv6 root user
  mysql_user: login_user={{ bc_rootuser }} login_password="{{ bc_rootpwd }}" name='{{ bc_rootuser }}' host={{ item }} state=absent
  with_items:
    - "::1"
  ignore_errors: true

- name: Ensure root access privileges are granted
  mysql_user: login_user={{ bc_rootuser }} login_password="{{ bc_rootpwd }}" user={{ bc_rootuser }} host="%" password="{{ bc_rootpwd }}" priv=*.*:GRANT,ALL state=present
  ignore_errors: true
