---

#Copyright 2016 ShapeBlue
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.
# Copyright (C) ShapeBlue Ltd - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Released by ShapeBlue <info@shapeblue.com>, April 2014

- name: Ensure prerequisite libselinux-python installed
  yum: name=libselinux-python state=installed
  tags:
    - kvm

- name: Ensure the Apache Cloudstack Repo file is configured
  template: src=cloudstack.repo.j2 dest=/etc/yum.repos.d/cloudstack.repo
  tags:
    - kvm
    - kvm-agent

- name: Ensure CloudStack packages are installed
  yum: name=cloudstack-agent state=present enablerepo=base
  tags:
    - kvm
    - kvm-agent

- name: Set selinux to permissive
  command: setenforce permissive
  changed_when: false
  tags:
    - kvm

- name: Ensure selinux is set permanently
  selinux: policy=targeted state=permissive
  tags:
    - kvm

- name: Install bridge utilities
  yum: name={{ item }} state=present enablerepo=base
  with_items:
    - bridge-utils
  tags:
    - kvm

#- name: set yum repo to local
#  template: src="{{ inventory_dir }}/templates/{{ item }}.j2" dest="/etc/yum.repos.d/{{item}}"
#  with_items:
#    - "epel.repo"
#    - "CentOS-Base.repo"
#  tags:
#    - kvm

- name: Install basic utilities and tools
  yum: name={{ item }} state=present enablerepo=base
  with_items:
    - bind-utils
    - bridge-utils
    - ntp
    - openssh-clients
    - pciutils
    - telnet
    - tcpdump
    - traceroute
    - nano
    - iftop
    - python-argparse
    - rpcbind
    - parted
  tags:
    - kvm

- name: ensure rpcbind in started
  service: name=rpcbind state=started enabled=yes

- name: Update libvirtd.conf - listen_tls
  lineinfile: dest=/etc/libvirt/libvirtd.conf regexp={{ item.regexp }} line={{ item.line }}  state=present
  with_items:
    - { regexp: "listen_tls", line: "listen_tls = 0" }
    - { regexp: "listen_tcp", line: "listen_tcp = 1" }
    - { regexp: "tcp_port", line: "tcp_port = \"16509\"" }
    - { regexp: "auth_tcp", line: "auth_tcp = \"none\"" }
    - { regexp: "mdns_adv", line: "mdns_adv = 0" }
  tags:
    - kvm
    - kvm-agent

- name: Update /etc/sysconfig/libvirtd - LIBVIRTD_ARGS
  lineinfile: dest=/etc/sysconfig/libvirtd regexp='LIBVIRTD_ARGS' line='LIBVIRTD_ARGS="--listen"' state=present
  tags:
    - kvm
    - kvm-agent

- name: Update /etc/libvirt/qemu.conf
  lineinfile: dest=/etc/libvirt/qemu.conf regexp='vnc_listen' line='vnc_listen = "0.0.0.0"' state=present
  tags:
    - kvm
    - kvm-agent

- name: Bugfix libvirt cpu issue on ACS 4.5 (CLOUDSTACK-8443)
  shell: sed -i -e '/cgroup\_controllers/d' /usr/lib64/python2.7/site-packages/cloudutils/serviceConfig.py
  when: ansible_distribution_major_version == "7"
  tags:
    - kvm
    - kvm-agent

- name: Add iptables rules
  shell: "iptables -I INPUT -p tcp -m tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - "22"
    - "1798"
    - "16509"
    - "5900:6100"
    - "49152:49216"
  tags:
    - kvm
    - kvm-agent

- name: IPtables save config
  shell: "iptables-save > /etc/sysconfig/iptables"
  tags:
    - kvm
    - kvm-agent

- name: KVM libvirtd restarted
  service: name=libvirtd state=restarted
  tags:
    - kvm
    - kvm-agent

